//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beRemote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("beRemote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MW_RibHelpBtnAbout {
            get {
                return ResourceManager.GetString("MW_RibHelpBtnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string MW_RibHelpBtnCommunity {
            get {
                return ResourceManager.GetString("MW_RibHelpBtnCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MW_RibHelpBtnHelp {
            get {
                return ResourceManager.GetString("MW_RibHelpBtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MW_RibHelpGrpHelp {
            get {
                return ResourceManager.GetString("MW_RibHelpGrpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Connections.
        /// </summary>
        public static string MW_RibMenuBtnConnections {
            get {
                return ResourceManager.GetString("MW_RibMenuBtnConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string MW_RibMenuBtnFavorites {
            get {
                return ResourceManager.GetString("MW_RibMenuBtnFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MW_RibMenuBtnSettings {
            get {
                return ResourceManager.GetString("MW_RibMenuBtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MW_RibMenuClose {
            get {
                return ResourceManager.GetString("MW_RibMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MW_RibServerBtnAdd {
            get {
                return ResourceManager.GetString("MW_RibServerBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string MW_RibServerBtnAddFolder {
            get {
                return ResourceManager.GetString("MW_RibServerBtnAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string MW_RibServerBtnCredentials {
            get {
                return ResourceManager.GetString("MW_RibServerBtnCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MW_RibServerBtnHistory {
            get {
                return ResourceManager.GetString("MW_RibServerBtnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MW_RibServerBtnRemove {
            get {
                return ResourceManager.GetString("MW_RibServerBtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string MW_RibServerBtnVpn {
            get {
                return ResourceManager.GetString("MW_RibServerBtnVpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is online.
        /// </summary>
        public static string MW_RibServerBtnWhoIsOnline {
            get {
                return ResourceManager.GetString("MW_RibServerBtnWhoIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string MW_RibServerGrpConnections {
            get {
                return ResourceManager.GetString("MW_RibServerGrpConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string MW_RibServerGrpFavorites {
            get {
                return ResourceManager.GetString("MW_RibServerGrpFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MW_RibServerGrpManage {
            get {
                return ResourceManager.GetString("MW_RibServerGrpManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MW_RibServerGrpMore {
            get {
                return ResourceManager.GetString("MW_RibServerGrpMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MW_RibSettingsGrpImport {
            get {
                return ResourceManager.GetString("MW_RibSettingsGrpImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MW_RibSettingsGrpProfile {
            get {
                return ResourceManager.GetString("MW_RibSettingsGrpProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superadmin.
        /// </summary>
        public static string MW_RibSettingsGrpSuperadmin {
            get {
                return ResourceManager.GetString("MW_RibSettingsGrpSuperadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MW_RibTabHeadHelp {
            get {
                return ResourceManager.GetString("MW_RibTabHeadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string MW_RibTabHeadServer {
            get {
                return ResourceManager.GetString("MW_RibTabHeadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MW_RibTabHeadSettings {
            get {
                return ResourceManager.GetString("MW_RibTabHeadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and Features.
        /// </summary>
        public static string MW_RibTabHeadToolsAndFeatures {
            get {
                return ResourceManager.GetString("MW_RibTabHeadToolsAndFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MW_RibTafGrpTools {
            get {
                return ResourceManager.GetString("MW_RibTafGrpTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string MW_TabTitleConnections {
            get {
                return ResourceManager.GetString("MW_TabTitleConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MW_TabTitleHistory {
            get {
                return ResourceManager.GetString("MW_TabTitleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beRemote v2.
        /// </summary>
        public static string MW_Title {
            get {
                return ResourceManager.GetString("MW_Title", resourceCulture);
            }
        }
    }
}
